import XCTest
import Security
@testable import Logos

/// WS3 S4: the iOS SPKI pin computation must match the Python adapter byte-for-byte. The fixture
/// certificate + expected pin are generated by plugins/logos/tls.py (spki_sha256_b64); if the
/// SPKI/hash scheme changes, regenerate both sides together (same discipline as LogosCryptoTests).
final class LogosCertPinningTests: XCTestCase {

    // Fixed self-signed EC P-256 cert (a public test vector, not a secret) and its Python pin.
    private static let fixturePEM = """
    -----BEGIN CERTIFICATE-----
    MIIBNjCB3KADAgECAgIwOTAKBggqhkjOPQQDAjAWMRQwEgYDVQQDDAtsb2dvcy5s
    b2NhbDAeFw0yNjAxMDEwMDAwMDBaFw0zNTEyMzAwMDAwMDBaMBYxFDASBgNVBAMM
    C2xvZ29zLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbSHh+1xpd3CZ
    vO+i1uUUkzSAjNvR0QgC90X4VfodXx6DDeR4za2fyQXJb5tN0Ccayunj33qcxiLG
    FF9nflpP66MaMBgwFgYDVR0RBA8wDYILbG9nb3MubG9jYWwwCgYIKoZIzj0EAwID
    SQAwRgIhANd8/oXn95qZT7bGgEoPg1I4LjulVKK6cYvNIJNrYkcMAiEAjE/dCFjn
    wrbzDep9iRPo3x5soKJ3olAy4eDpG39WN/Y=
    -----END CERTIFICATE-----
    """

    private static let expectedPin = "LMW4Vn0X9vxobYbwfcp4mOnF1v8deu2yltvTA7piDZo="

    private func fixtureCertificate() throws -> SecCertificate {
        let der = try XCTUnwrap(derFromPEM(Self.fixturePEM))
        return try XCTUnwrap(SecCertificateCreateWithData(nil, der as CFData))
    }

    private func derFromPEM(_ pem: String) -> Data? {
        let body = pem
            .components(separatedBy: .newlines)
            .filter { !$0.contains("BEGIN CERTIFICATE") && !$0.contains("END CERTIFICATE") }
            .joined()
        return Data(base64Encoded: body)
    }

    func testSPKIPinMatchesPythonKnownAnswer() throws {
        let certificate = try fixtureCertificate()
        let pin = try XCTUnwrap(LogosCertPinning.spkiSHA256(of: certificate))
        XCTAssertEqual(pin, Self.expectedPin, "iOS SPKI pin must match plugins/logos/tls.py")
        XCTAssertEqual(pin.count, 44)  // base64 SHA-256
    }

    func testPinsMatchIsConstantTimeEquality() {
        XCTAssertTrue(LogosCertPinning.pinsMatch(Self.expectedPin, Self.expectedPin))
        XCTAssertFalse(LogosCertPinning.pinsMatch(Self.expectedPin, "different-pin-value"))
        // Differing length must be rejected, not crash.
        XCTAssertFalse(LogosCertPinning.pinsMatch(Self.expectedPin, "short"))
    }

    // MARK: - Pairing deep-link pin decode + settings persistence

    private func pairingURL(includePin: Bool) -> URL {
        var payload: [String: Any] = [
            "v": 1,
            "adapter_url": "wss://logos.example:8765/logos",
            "device_id": "ios-abcdef12",
            "pair_token": "tok-123",
            "expires_at": 1_778_760_000.0,
            "autoconnect": true,
        ]
        if includePin { payload["cert_spki_sha256"] = Self.expectedPin }
        let data = try! JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys])
        return URL(string: "logos://pair#\(data.base64EncodedString())")!
    }

    func testPairingRouteDecodesCertPin() throws {
        let route = try XCTUnwrap(LogosPairingRoute.from(url: pairingURL(includePin: true)))
        XCTAssertEqual(route.certSPKISHA256, Self.expectedPin)
    }

    func testPairingRouteWithoutPinIsNil() throws {
        let route = try XCTUnwrap(LogosPairingRoute.from(url: pairingURL(includePin: false)))
        XCTAssertNil(route.certSPKISHA256)
    }

    func testSettingsPersistsCertPinRoundTrip() throws {
        let defaults = try XCTUnwrap(UserDefaults(suiteName: "logos.tests.\(UUID().uuidString)"))
        var settings = LogosSettings(environment: [:], userDefaults: defaults)
        settings.certSPKISHA256 = Self.expectedPin
        settings.persist(userDefaults: defaults)

        let reloaded = LogosSettings(environment: [:], userDefaults: defaults)
        XCTAssertEqual(reloaded.certSPKISHA256, Self.expectedPin)

        // Clearing the pin removes it from persistence.
        var cleared = reloaded
        cleared.certSPKISHA256 = ""
        cleared.persist(userDefaults: defaults)
        XCTAssertEqual(LogosSettings(environment: [:], userDefaults: defaults).certSPKISHA256, "")
    }
}
